author: Mike Slinn
compress_html:
  blanklines: false
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  profile: false
  startings: [html, head, body]
domain: bogus.jekylldemo.com
email: bogus@jekylldemo.com
exclude:  # Wildcards are not supported yet https://github.com/jekyll/jekyll-watch/pull/93
  - .git
  - .github
  - .gitignore
  - .jekyll-cache
  - .jekyll-metadata
  - .ruby-version
  - .vscode
  - BingSiteAuth.xml
  - Gemfile
  - Gemfile.lock
  - README.md
ignore_theme_config: true
liquid:
  error_mode: strict
  # strict_filters: true
  # strict_variables: true
plugin_loggers:
  PluginMetaLogger: warn
  CleanHook: warn
  DocumentHooks: warn
  PluginLogger: off
  Raw::InlineTag: debug     # Notice the module name is specified as well as the class name
  Support::InlineTag: debug # Notice the module name is specified as well as the class name
  PageHooks: warn
  PostHooks: warn
  SiteHooks: warn
permalink: "/blog/:year/:month/:day/:title:output_ext"
plugins: # Use file name of the plugin entry point, not the gem name
  - classifier-reborn
  - html-proofer
  - jekyll
  - jekyll_plugin_logger
sass:
  style: compressed
title: jekyll_plugin_logger Demonstration
url: https://bogus.jekylldemo.com
